### PR TITLE
[Issue #3522] refine fix for pagination showing with no results

### LINKED ISSUE #3522: Pagination can appear with no search results
### Summary

It is possible to get search into a state where the app shows no search results, but does show a pagination menu.

Image

It is expected that the pagination menu would not appear if there are no search results for a given search.

Note that this reproducible only if you filter down to zero results from a page other than the first page of search results.

### Reproducibility

I tried multiple times and saw the bug every time

### How to reproduce the bug

* visit https://simpler.grants.gov/search?refresh=true&page=2 (puts you on page two of the default search
* check the Agency filter for "Consumer Product Safety Commission"

### Browser

Not applicable

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by doug-s-nava**
## Summary
Fixes #3522

## Changes proposed
While the client facing issue for the bug mentioned in the ticket was fixed in https://github.com/HHS/simpler-grants-gov/pull/3524 this provides a more comprehensive fix by correcting some slightly funky behavior in pagination related components

## Context for reviewers
1. start the app on this branch
2. run a search with all kinds of different pagination scenarios
3. _VERIFY_: all pagination related behavior works, pagination continues to not appear if there are no search results

### CODE REVIEW

File: frontend/src/components/search/SearchSortBy.tsx [hunk 1]
```diff
@@ -52,11 +45,13 @@ export default function SearchSortBy({
     },
   ];
 
-  const handleChange = (event: React.ChangeEvent<HTMLSelectElement>) => {
-    const newValue = event.target.value;
-    updateTotalResults(totalResults);
```
Comment (doug-s-nava) [inline frontend/src/components/search/SearchSortBy.tsx:57]: there's no need to set total results in multiple places in the app, since both of these components are responding to the same request

File: frontend/src/components/search/SearchPagination.tsx [hunk 2]
```diff
@@ -14,40 +14,61 @@ export enum PaginationPosition {
...
+
+  useEffect(() => {
+    if (!loading) {
+      updateTotalResults(String(totalResults));
+    }
+  }, [updateTotalResults, totalResults, loading]);
 
   const updatePage = (page: number) => {
-    updateTotalPages(String(total));
-    updateTotalResults(totalResults);
```
Comment (doug-s-nava) [inline frontend/src/components/search/SearchPagination.tsx:41]: with these functions only being called in `updatePage` the client side pagination state was only being updated on pagination clicks, not in response to the search results updating from the completed API request. With this new setup, the state will be set purely based on the results of the search request whenever a new request is made

File: frontend/src/app/[locale]/search/QueryProvider.tsx [hunk 3]
```diff
@@ -3,7 +3,7 @@
 import { useSearchParams } from "next/navigation";
 import { createContext, useCallback, useMemo, useState } from "react";
 
-interface QueryContextParams {
+export interface QueryContextParams {
```
Comment (acouch) [inline frontend/src/app/[locale]/search/QueryProvider.tsx:6]: Is there a reason to export this? Didn't see it called elsewhere

**Review by acouch — DISMISSED** [review]
👍🏿

File: frontend/src/app/[locale]/search/QueryProvider.tsx (hunk 3 above)
Comment (doug-s-nava) [reply frontend/src/app/[locale]/search/QueryProvider.tsx:6]: good catch, this is left over from a previous idea. Removing.

**Review by acouch — APPROVED** [review]
