### PR TITLE
[Issue #1545] Layout improvements

### LINKED ISSUE #1545: [Task:] Update search layout to match Figma
Page layout of Search should match the Figma design 

| Code | Figma |
| --- | --- |
| Image | Image | 

- Add missing "terms" `label`
- Position sorting `select` top-right, next to count
- Fix indentation of breadcrumbs
- Match CTA font 
- Adjust spacing between items
- Right-align the award meta

_*Note: pagination is wrong in the Figma; we're using the unbounded variant which does not default to showing the last page_

### PR DESCRIPTION
**Pull request by andycochran**
## Summary
Fixes #1545 

## Changes proposed
Update the page layout of Search to match the Figma design: 
- Add missing "Search terms" label + help text 
- Position sorting select top-right, next to count
- Fix indentation of breadcrumbs
- Match CTA font
- Adjust spacing between items
- Right-align the award meta

## Additional information

| Before | After | 
| --- | --- | 
| image | image |

### CODE REVIEW

File: frontend/src/app/search/SearchForm.tsx [hunk 1]
```diff
@@ -64,14 +64,12 @@ export function SearchForm({
             />
           </div>
           <div className="tablet:grid-col-8">
+            <SearchResultsHeader
+              formRef={formRef}
+              searchResultsLength={searchResults.pagination_info.total_records}
+              initialQueryParams={sortbyQueryParams}
+            />
```
Comment (andycochran) [inline frontend/src/app/search/SearchForm.tsx:71]: Moving this outside the `.usa-prose` which adds unnecessary styles

File: frontend/src/components/search/SearchBar.tsx [hunk 2]
```diff
@@ -1,5 +1,6 @@
 "use client";
 
+import { Icon } from "@trussworks/react-uswds";
```
Comment (andycochran) [inline frontend/src/components/search/SearchBar.tsx:3]: Adding the icon and appropriate classes makes the button responsive so that small screens shows the magnifying glass icon and larger screens shows the word "Search"

File: frontend/src/components/search/SearchBar.tsx [hunk 3]
```diff
@@ -16,27 +17,35 @@ export default function SearchBar({ initialQueryParams }: SearchBarProps) {
...
-        Search
+    <div className="margin-top-5 margin-bottom-2">
+      <label
+        htmlFor="query"
+        className="font-sans-lg display-block margin-bottom-2"
+      >
+        <span className="text-bold">Search terms </span>
+        <small className="display-inline-block">
+          Enter keywords, opportunity numbers, or assistance listing numbers
+        </small>
```
Comment (andycochran) [inline frontend/src/components/search/SearchBar.tsx:28]: Moving the `label` outside the `.usa-search` to avoid the flex grid styles it gets that force it left of the `input`

File: frontend/src/components/search/SearchCallToAction.tsx [hunk 4]
```diff
@@ -7,19 +7,20 @@ import { SEARCH_CRUMBS } from "../../constants/breadcrumbs";
 
 const SearchCallToAction: React.FC = () => {
   return (
-    <GridContainer>
-      {/* TODO: BetaAlert Breadcrumbs */}
+    <>
```
Comment (andycochran) [inline frontend/src/components/search/SearchCallToAction.tsx:10]: The `Breadcrumbs` component shouldn't be inside the `GridContainer`, as the component has one itself. Nesting a `GridContainer` causes unnecessary extra padding

**Review by coilysiren — APPROVED** [review]
👍🏼 !

File: frontend/src/components/search/SearchResultsHeader.tsx [hunk 5]
```diff
@@ -14,15 +14,17 @@ const SearchResultsHeader: React.FC<SearchResultsHeaderProps> = ({
...
-        <h2>{searchResultsLength} Opportunities</h2>
+    <div className="grid-row">
+      <h2 className="tablet-lg:grid-col-fill margin-top-5 tablet-lg:margin-top-2 tablet-lg:margin-bottom-0">
+        {searchResultsLength} Opportunities
+      </h2>
+      <div className="tablet-lg:grid-col-auto">
+        <SearchSortyBy
+          formRef={formRef}
+          initialQueryParams={initialQueryParams}
+        />
```
Comment (andycochran) [inline frontend/src/components/search/SearchResultsHeader.tsx:25]: Putting these in a grid and nixing the unnecessary divs

File: frontend/src/components/search/SearchResultsListItem.tsx [hunk 6]
```diff
@@ -111,15 +111,19 @@ export default function SearchResultsListItem({
...
+            >
               <strong>Award Ceiling:</strong>{" "}
-              <span className="desktop:display-block desktop:font-sans-lg text-ls-neg-3">
+              <span className="desktop:display-block desktop:font-sans-lg text-ls-neg-3 text-right">
                 ${opportunity?.summary?.award_ceiling?.toLocaleString() || "--"}
               </span>
             </span>
-            <span className="display-block desktop:text-right">
+            <span
+              className={`${metadataBorderClasses} desktop:display-block text-right desktop:margin-right-0 desktop:padding-right-0`}
```
Comment (andycochran) [inline frontend/src/components/search/SearchResultsListItem.tsx:125]: Using the `metadataBorderClasses` so that the award meta gets the responsive styles that put a border between items with they're short enough to appear on one line. The `.text-right` classes only apply on desktop when we override the `display`

**Review by acouch — APPROVED** [review]
